name: Add new comic

on:
  workflow_dispatch:
    inputs:
      comic_id:
        description: The id of the comic you want to add
        required: true
      comic_source:
        description: The source from which the comic must be pulled ("mangapark", "omegascans", ...)
        required: true
      comic_chapter:
        description: The chapter number from which the comic must bu pulled
        default: "0"

jobs:
  add-new-comic:
    permissions:
      contents: write
    name: Add new comic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install NPM Packages
        run: npm ci

      - name: Add new comic
        id: add-new-comic
        uses: ./.github/actions/add-new-comic.yaml
        with:
          comic_id: ${{ inputs.comic_id }}
          comic_source: ${{ inputs.comic_source }}
          comic_chapter: ${{ inputs.comic_chapter }}

      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "chore: :heavy_plus_sign: Added `${{ steps.add-new-comic.outputs.comic_name }}`"
