name: Look for updates

on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  look-for-updates:
    permissions:
      contents: write
    name: Look for updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} @ ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install NPM Packages
        run: npm ci

      - name: Look for updates
        run: npm start
        env:
          MAILTRAP_TOKEN: ${{ secrets.MAILTRAP_TOKEN }}
          EMAIL_SENDER: ${{ vars.EMAIL_SENDER }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

      - name: Commit & Push changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          add: "./data/mangas.json"
          message: "chore: :wrench: Updated the read mangas"
